export const FETCH_STATE_FETCHING = "FETCH_STATE_FETCHING";
export const FETCH_STATE_FETCHED = "FETCH_STATE_FETCHED";
export const FETCH_STATE_ERROR = "FETCH_STATE_ERROR";
export const FETCH_STATE_NEUTRAL = "FETCH_STATE_NEUTRAL";